
backend:
  name: test-repo
media_library:
  name: cloudinary
  config:
    cloud_name: dta9vptzh
    api_key: 651661895481873
    multiple: true
public_folder: /image
publish_mode: editorial_workflow

collections:
  - name: product
    label: Products
    folder: "content/auteurs"
    create: true
    fields:
      - {name: title, label: Title, widget: "string"}
      - {name: sku, label: Sku, widget: "string"}
      - {name: description, label: Naam, widget:"string"}
      - {label: "Price", name: "price", widget: "string", pattern: ['(?<=^| )\d+(\.\d+)?(?=$| )', "must be a number"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["paarden","stallen","dekjes"]
      - name: image
        label: Image
        widget: 'image'
        valueField: "{{slug}}"
